" ===================================
" @gmu113r: 
" VIM configurations file
" ===================================

set nocompatible
set termguicolors
set relativenumber

if has('syntax')
  syntax on
endif

set hidden
set wildmenu
set showcmd
set hlsearch
set ignorecase
set smartcase
set autoindent

set viminfofile=NONE
colorscheme GruberDarker
set guifont=Iosevka:h14
